"use strict";
const $=id=>document.getElementById(id), esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c])), toast=m=>{$("playerToast").textContent=m;$("playerToast").classList.add("show");setTimeout(()=>$("playerToast").classList.remove("show"),2800)};
let user=null,groups=[],activeGroup=null;
async function loadData(){const [{data:profile},{data:events},{data:memberships}]=await Promise.all([cobrasDb.from("profiles").select("*").eq("id",user.id).maybeSingle(),cobrasDb.from("team_events").select("*").order("starts_at"),cobrasDb.from("chat_members").select("group_id,chat_groups(*)").eq("user_id",user.id)]);if(profile?.role==="admin"){await cobrasCloud.auth.signOut();location.reload();return}const matches=(events||[]).filter(e=>e.kind==="match"),trainings=(events||[]).filter(e=>e.kind==="training");$("playerIdentity").textContent=`${profile?.display_name||user.email} · ${profile?.role||"joueur"}`;$("playerMatches").innerHTML=matches.length?matches.map(e=>`<div class="admin-match-item"><span><b>${esc(new Date(e.starts_at).toLocaleString("fr-FR"))}</b> · Cobras vs ${esc(e.opponent||"adversaire")}<small>${esc(e.location||"")}</small></span></div>`).join(""):"<p class=\"admin-empty\">Aucun match.</p>";$("playerTrainings").innerHTML=trainings.length?trainings.map(e=>`<div class="admin-match-item"><span><b>${esc(new Date(e.starts_at).toLocaleString("fr-FR"))}</b> · ${esc(e.title)}<small>${esc(e.location||"")}</small></span><button class="button button-outline small presence-button" data-event="${e.id}">Présent</button></div>`).join(""):"<p class=\"admin-empty\">Aucun entraînement.</p>";groups=(memberships||[]).map(m=>m.chat_groups).filter(Boolean);$("groupList").innerHTML=groups.length?groups.map(g=>`<button class="group-button" data-group="${g.id}">${esc(g.name)}</button>`).join(""):"<p class=\"admin-empty\">Aucune conversation.</p>"}
async function openGroup(id){activeGroup=id;const group=groups.find(g=>g.id===id);$("chatTitle").textContent=group?group.name:"Conversation";$("messageForm").hidden=false;const {data}=await cobrasDb.from("chat_messages").select("*,profiles(display_name)").eq("group_id",id).order("created_at");$("messageList").innerHTML=(data||[]).map(m=>`<div class="message-item"><b>${esc(m.profiles?.display_name||"Joueur")}</b><p>${esc(m.body)}</p><time>${esc(new Date(m.created_at).toLocaleString("fr-FR"))}</time></div>`).join("")||"<p class=\"admin-empty\">Aucun message.</p>"}
$("playerLoginForm").addEventListener("submit",async e=>{e.preventDefault();const {data,error}=await cobrasCloud.auth.signInWithPassword({email:$("playerEmail").value.trim(),password:$("playerPassword").value});if(error)return toast(error.message);user=data.user;await showDashboard()});
$("playerSignupForm").addEventListener("submit",async e=>{e.preventDefault();const {data,error}=await cobrasCloud.auth.signUp({email:$("signupEmail").value.trim(),password:$("signupPassword").value,options:{data:{display_name:$("signupName").value.trim(),role:"player"}}});if(error)return toast(error.message);toast(data.session?"Compte joueur créé.":"Compte créé : confirme ton email.");if(data.session){user=data.user;await showDashboard()}});
async function showDashboard(){$("playerLogin").hidden=true;$("playerDashboard").hidden=false;$("playerLogout").hidden=false;await loadData()}
$("playerLogout").addEventListener("click",async()=>{await cobrasCloud.auth.signOut();location.reload()});
document.addEventListener("click",e=>{if(e.target.dataset.tab){$("agendaTab").hidden=e.target.dataset.tab!=="agenda";$("chatTab").hidden=e.target.dataset.tab!=="chat"}if(e.target.dataset.group)openGroup(e.target.dataset.group);if(e.target.dataset.event)toast("Présence enregistrée prochainement après activation de la table des présences.")});
$("messageForm").addEventListener("submit",async e=>{e.preventDefault();if(!activeGroup)return;const body=$("messageInput").value.trim();const {error}=await cobrasDb.from("chat_messages").insert({group_id:activeGroup,author_id:user.id,body});if(error)return toast(error.message);$("messageInput").value="";await openGroup(activeGroup)});
cobrasCloud.auth.getUser().then(({data})=>{if(data.user){user=data.user;showDashboard()}});
