"use strict";
const newsKey="cobras-paris-news-v2",matchesKey="cobras-paris-matches-v1",usersKey="cobras-paris-users-v1",activityKey="cobras-paris-activity-v1";
const $=id=>document.getElementById(id), read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}}, esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const defaultNews=[{id:1,category:"Vie du club",title:"Les Cobras font leur rentrée",excerpt:"La saison démarre fort. Retrouvez-nous dès septembre pour les premiers entraînements.",date:"28 AOÛT 2025"},{id:2,category:"Recrutement",title:"Le recrutement est ouvert",excerpt:"Envie de découvrir le football américain ? Les séances d'essai sont ouvertes à tous les niveaux.",date:"20 AOÛT 2025"},{id:3,category:"Événement",title:"Un club, une famille",excerpt:"Retour en images sur la journée portes ouvertes qui a réuni toute la communauté Cobra.",date:"12 AOÛT 2025"}];
const defaultMatches=[{id:1,date:"2025-09-14",opponent:"Meteors",venue:"Stade Georges Carpentier · Paris 13e",type:"À domicile"},{id:2,date:"2025-09-28",opponent:"Warriors",venue:"Stade du Parc · Cergy",type:"À l'extérieur"},{id:3,date:"2025-10-12",opponent:"Lions",venue:"Stade Georges Carpentier · Paris 13e",type:"À domicile"}];
let news=read(newsKey,defaultNews),matches=read(matchesKey,defaultMatches),users=read(usersKey,[{id:1,name:"Staff principal",email:"cobrasdeparis@yahoo.com",role:"Administrateur"}]),activities=read(activityKey,[]);
const save=async()=>{localStorage.setItem(newsKey,JSON.stringify(news));localStorage.setItem(matchesKey,JSON.stringify(matches));localStorage.setItem(usersKey,JSON.stringify(users));localStorage.setItem(activityKey,JSON.stringify(activities));try{await Promise.all([window.cobrasCloud.save("news",news),window.cobrasCloud.save("matches",matches),window.cobrasCloud.save("users",users),window.cobrasCloud.save("activities",activities)])}catch(error){console.error("Synchronisation Supabase impossible.",error);toast("Synchronisation cloud impossible.")}};
const toast=m=>{$("toast").textContent=m;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2800)};
window.addEventListener("pageshow",()=>{$("loginEmail").value="";$("loginPassword").value=""});
let installPrompt=null;
window.addEventListener("beforeinstallprompt",event=>{event.preventDefault();installPrompt=event;$("installStaff").hidden=false});
$("installStaff").addEventListener("click",async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$("installStaff").hidden=true});
window.addEventListener("appinstalled",()=>{$("installStaff").hidden=true;toast("Application staff installée.")});
const past=v=>new Date(`${v}T12:00:00`)<new Date(new Date().setHours(0,0,0,0));
function log(action){activities.unshift({id:Date.now(),user:"Staff principal",action,date:new Date().toLocaleString("fr-FR",{dateStyle:"short",timeStyle:"short"})});activities=activities.slice(0,40)}
function render(){ $("newsCount").textContent=news.length;$("matchCount").textContent=matches.length;$("adminNewsList").innerHTML=news.map(n=>`<div class="admin-news-item"><span>${esc(n.title)}</span>${n.id>3?`<button data-delete-news="${n.id}">Supprimer</button>`:""}</div>`).join("");$("adminMatchList").innerHTML=matches.map(m=>`<div class="admin-match-item"><span>${esc(m.date)} · Cobras vs ${esc(m.opponent)}</span><button data-delete-match="${m.id}">Supprimer</button></div>`).join("");$("adminUserList").innerHTML=users.map(u=>`<div class="admin-user-item"><span><b>${esc(u.name)}</b><small>${esc(u.email)} · ${esc(u.role)}</small></span>${u.id===1?"":`<button data-delete-user="${u.id}">Supprimer</button>`}</div>`).join("");$("activityLog").innerHTML=activities.length?activities.map(a=>`<div class="activity-item"><span><b>${esc(a.user)}</b> · ${esc(a.action)}</span><time>${esc(a.date)}</time></div>`).join(""):'<p class="admin-empty">Aucune modification enregistrée.</p>'}
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();const {error}=await window.cobrasCloud.auth.signInWithPassword({email:$("loginEmail").value.trim(),password:$("loginPassword").value});if(error){console.error("Connexion Supabase refusée.",error);toast(error.message||"Connexion impossible.");return}$("loginView").hidden=true;$("dashboardView").hidden=false;const cloudData=await Promise.all([window.cobrasCloud.load("news",news),window.cobrasCloud.load("matches",matches),window.cobrasCloud.load("users",users),window.cobrasCloud.load("activities",activities)]);if(cloudData[0].length)news=cloudData[0];if(cloudData[1].length)matches=cloudData[1];if(cloudData[2].length)users=cloudData[2];if(cloudData[3].length)activities=cloudData[3];log("s'est connecté à l'espace privé");await save();render();toast("Bienvenue dans l’espace staff.")});
$("logoutButton").addEventListener("click",()=>{$("dashboardView").hidden=true;$("loginView").hidden=false});
$("newsForm").addEventListener("submit",e=>{e.preventDefault();const title=$("newsTitle").value.trim();news.unshift({id:Date.now(),category:$("newsCategory").value,title,excerpt:$("newsExcerpt").value.trim(),date:new Date().toLocaleDateString("fr-FR",{day:"2-digit",month:"long",year:"numeric"}).toUpperCase()});log(`a publié l'annonce « ${title} »`);save();render();e.target.reset();toast("Annonce publiée sur le site public.")});
$("matchForm").addEventListener("submit",e=>{e.preventDefault();matches.push({id:Date.now(),date:$("matchDate").value,opponent:$("matchOpponent").value.trim(),venue:$("matchVenue").value.trim(),type:$("matchType").value,scoreHome:$("matchScoreHome").value===""?null:Number($("matchScoreHome").value),scoreAway:$("matchScoreAway").value===""?null:Number($("matchScoreAway").value)});log(`a ajouté le match Cobras vs ${$("matchOpponent").value.trim()}`);save();render();e.target.reset();toast("Match ajouté au calendrier.")});
document.addEventListener("click",e=>{const n=Number(e.target.dataset.deleteNews),m=Number(e.target.dataset.deleteMatch),u=Number(e.target.dataset.deleteUser);if(n){news=news.filter(x=>x.id!==n);log("a supprimé une annonce");save();render()}if(m){matches=matches.filter(x=>x.id!==m);log("a supprimé un match");save();render()}if(u){users=users.filter(x=>x.id!==u);log("a supprimé un utilisateur");save();render()}});
$("userForm").addEventListener("submit",async e=>{e.preventDefault();const email=$("userEmail").value.trim(),password=$("userPassword").value,name=$("userName").value.trim(),role=$("userRole").value;if(users.some(u=>u.email.toLowerCase()===email.toLowerCase()))return toast("Cet email est déjà utilisé.");const {data:{session:adminSession}}=await window.cobrasCloud.auth.getSession();const {data,error}=await window.cobrasCloud.auth.signUp({email,password,options:{data:{name,role}}});if(error)return toast(error.message||"Création du compte impossible.");if(adminSession&&data.session)await window.cobrasCloud.auth.setSession(adminSession);users.push({id:Date.now(),name,email,role});log(`a créé le compte ${name}`);await save();render();e.target.reset();toast(data.session?"Utilisateur créé.":"Utilisateur créé : confirmation email nécessaire.")});
$("exportData").addEventListener("click",()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({news,matches,users,activities},null,2)],{type:"application/json"})),a=document.createElement("a");a.href=url;a.download=`cobras-paris-sauvegarde-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);log("a exporté une sauvegarde complète");save();render()});
$("importData").addEventListener("change",async e=>{const [file]=e.target.files;if(!file)return;try{const data=JSON.parse(await file.text());if(!Array.isArray(data.news)||!Array.isArray(data.matches)||!Array.isArray(data.users)||!Array.isArray(data.activities))throw Error("Format invalide.");({news,matches,users,activities}=data);log("a importé une sauvegarde complète");save();render();toast("Sauvegarde restaurée.")}catch(err){toast(err.message)}e.target.value=""});
render();
