"use strict";
const $ = (id) => document.getElementById(id);
const esc = (value) => String(value).replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[char]));
const keys = { news: "cobras-paris-news-v2", matches: "cobras-paris-matches-v1", users: "cobras-paris-users-v1", activities: "cobras-paris-activity-v1" };
const read = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) || fallback; } catch { return fallback; } };
let news = read(keys.news, []), matches = read(keys.matches, []), users = read(keys.users, []), activities = read(keys.activities, []), currentRole = "";
const toast = (message) => { $("toast").textContent = message; $("toast").classList.add("show"); setTimeout(() => $("toast").classList.remove("show"), 2800); };
const saveLocal = () => { localStorage.setItem(keys.news, JSON.stringify(news)); localStorage.setItem(keys.matches, JSON.stringify(matches)); localStorage.setItem(keys.users, JSON.stringify(users)); localStorage.setItem(keys.activities, JSON.stringify(activities)); };
const log = (action) => { activities.unshift({ id: Date.now(), user: $("loginEmail").value.trim(), action, date: new Date().toLocaleString("fr-FR", { dateStyle: "short", timeStyle: "short" }) }); activities = activities.slice(0, 40); };
async function cloudSave() { saveLocal(); try { await Promise.all(Object.entries({ news, matches, users, activities }).map(([key, value]) => window.cobrasCloud.save(key, value))); } catch (error) { console.error("Synchronisation Supabase impossible.", error); toast("Synchronisation cloud impossible."); } }
async function loadCloud() { try { const values = await Promise.all(Object.entries({ news, matches, users, activities }).map(([key, value]) => window.cobrasCloud.load(key, value))); [news, matches, users, activities] = values.map((value, index) => Array.isArray(value) && value.length ? value : Object.values({ news, matches, users, activities })[index]); } catch (error) { console.error("Lecture Supabase impossible.", error); } }
async function applyPermissions() { const { data: sessionData } = await window.cobrasCloud.auth.getSession(); if (!sessionData.session) return; const { data: profile } = await cobrasDb.from("profiles").select("role").eq("id", sessionData.session.user.id).maybeSingle(); currentRole = profile?.role || "player"; document.querySelectorAll(".coach-only").forEach((element) => { element.hidden = currentRole !== "coach"; }); }
function render() { $("newsCount").textContent = news.length; $("matchCount").textContent = matches.length; $("adminNewsList").innerHTML = news.map((item) => `<div class="admin-news-item"><span>${esc(item.title)}</span>${item.id > 3 ? `<button data-delete-news="${item.id}">Supprimer</button>` : ""}</div>`).join(""); $("adminMatchList").innerHTML = matches.map((item) => `<div class="admin-match-item"><span>${esc(item.date)} · Cobras vs ${esc(item.opponent)}</span><button data-delete-match="${item.id}">Supprimer</button></div>`).join(""); $("adminUserList").innerHTML = users.map((item) => `<div class="admin-user-item"><span><b>${esc(item.name)}</b><small>${esc(item.email)} · ${esc(item.role)}</small></span>${item.id === 1 ? "" : `<button data-delete-user="${item.id}">Supprimer</button>`}</div>`).join(""); $("activityLog").innerHTML = activities.length ? activities.map((item) => `<div class="activity-item"><span><b>${esc(item.user)}</b> · ${esc(item.action)}</span><time>${esc(item.date)}</time></div>`).join("") : '<p class="admin-empty">Aucune modification enregistrée.</p>'; }
$("loginForm").addEventListener("submit", async (event) => { event.preventDefault(); const { error } = await window.cobrasCloud.auth.signInWithPassword({ email: $("loginEmail").value.trim(), password: $("loginPassword").value }); if (error) return toast(error.message); await loadCloud(); $("loginView").hidden = true; $("dashboardView").hidden = false; await applyPermissions(); log("s'est connecté à l'espace privé"); await cloudSave(); render(); });
$("logoutButton").addEventListener("click", async () => { await window.cobrasCloud.auth.signOut(); location.reload(); });
$("newsForm").addEventListener("submit", async (event) => { event.preventDefault(); const title = $("newsTitle").value.trim(); news.unshift({ id: Date.now(), category: $("newsCategory").value, title, excerpt: $("newsExcerpt").value.trim(), date: new Date().toLocaleDateString("fr-FR", { day: "2-digit", month: "long", year: "numeric" }).toUpperCase() }); log(`a publié l'annonce « ${title} »`); await cloudSave(); render(); event.target.reset(); toast("Annonce publiée."); });
$("matchForm").addEventListener("submit", async (event) => { event.preventDefault(); matches.push({ id: Date.now(), date: $("matchDate").value, opponent: $("matchOpponent").value.trim(), venue: $("matchVenue").value.trim(), type: $("matchType").value, scoreHome: $("matchScoreHome").value === "" ? null : Number($("matchScoreHome").value), scoreAway: $("matchScoreAway").value === "" ? null : Number($("matchScoreAway").value) }); log("a ajouté un match"); await cloudSave(); render(); event.target.reset(); toast("Match ajouté."); });
$("userForm").addEventListener("submit", async (event) => { event.preventDefault(); const email = $("userEmail").value.trim(), password = $("userPassword").value, name = $("userName").value.trim(), role = $("userRole").value; if (users.some((item) => item.email.toLowerCase() === email.toLowerCase())) return toast("Cet email est déjà utilisé."); const { error } = await window.cobrasCloud.auth.signUp({ email, password, options: { data: { display_name: name, app_role: "staff", role } } }); if (error) return toast(error.message); users.push({ id: Date.now(), name, email, role }); log(`a créé l'utilisateur ${name}`); await cloudSave(); render(); event.target.reset(); toast("Utilisateur créé."); });
$("roleForm").addEventListener("submit", async (event) => { event.preventDefault(); if (currentRole !== "admin") return toast("Seul un administrateur peut modifier les rôles."); const email = $("coachEmail").value.trim().toLowerCase(), password = $("staffConfirmPassword").value; const { data: sessionData } = await window.cobrasCloud.auth.getSession(); if (!sessionData.session) return toast("Session staff expirée."); const { error: verifyError } = await window.cobrasCloud.auth.signInWithPassword({ email: sessionData.session.user.email, password }); if (verifyError) return toast("Mot de passe staff incorrect."); const { data: profile } = await cobrasDb.from("profiles").select("id").eq("email", email).maybeSingle(); if (!profile) return toast("Compte joueur introuvable."); const { error } = await cobrasDb.from("profiles").update({ role: "coach" }).eq("id", profile.id); if (error) return toast(error.message); log(`a promu ${email} entraîneur`); await cloudSave(); event.target.reset(); toast("Compte passé entraîneur."); });
$("teamEventForm").addEventListener("submit", async (event) => { event.preventDefault(); if (currentRole !== "coach") return toast("Réservé aux entraîneurs."); const { data: sessionData } = await window.cobrasCloud.auth.getSession(); const { error } = await cobrasDb.from("team_events").insert({ kind: $("teamEventKind").value, title: $("teamEventTitle").value.trim(), opponent: $("teamEventOpponent").value.trim() || null, starts_at: new Date($("teamEventDate").value).toISOString(), location: $("teamEventLocation").value.trim() || null, created_by: sessionData.session.user.id }); if (error) return toast(error.message); toast("Événement ajouté."); event.target.reset(); });
$("groupForm").addEventListener("submit", async (event) => { event.preventDefault(); if (currentRole !== "coach") return toast("Réservé aux entraîneurs."); const { data: sessionData } = await window.cobrasCloud.auth.getSession(); const { data: group, error } = await cobrasDb.from("chat_groups").insert({ name: $("groupName").value.trim(), created_by: sessionData.session.user.id }).select().single(); if (error) return toast(error.message); const emails = $("groupMembers").value.split(",").map((value) => value.trim().toLowerCase()).filter(Boolean); const { data: profiles } = await cobrasDb.from("profiles").select("id,email").in("email", emails); await cobrasDb.from("chat_members").insert([{ group_id: group.id, user_id: sessionData.session.user.id, added_by: sessionData.session.user.id }, ...(profiles || []).map((profile) => ({ group_id: group.id, user_id: profile.id, added_by: sessionData.session.user.id }))]); toast("Groupe créé."); event.target.reset(); });
document.addEventListener("click", async (event) => { const newsId = Number(event.target.dataset.deleteNews), matchId = Number(event.target.dataset.deleteMatch), userId = Number(event.target.dataset.deleteUser); if (newsId) news = news.filter((item) => item.id !== newsId); if (matchId) matches = matches.filter((item) => item.id !== matchId); if (userId) users = users.filter((item) => item.id !== userId); if (newsId || matchId || userId) { log("a supprimé un élément"); await cloudSave(); render(); } });
$("exportData").addEventListener("click", () => { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([JSON.stringify({ news, matches, users, activities }, null, 2)], { type: "application/json" })); link.download = "cobras-paris-sauvegarde.json"; link.click(); });
$("importData").addEventListener("change", async (event) => { const [file] = event.target.files; if (!file) return; try { const data = JSON.parse(await file.text()); if (!Array.isArray(data.news) || !Array.isArray(data.matches) || !Array.isArray(data.users) || !Array.isArray(data.activities)) throw new Error("Format invalide."); ({ news, matches, users, activities } = data); log("a importé une sauvegarde"); await cloudSave(); render(); toast("Sauvegarde restaurée."); } catch (error) { toast(error.message); } event.target.value = ""; });
render();
