create table if not exists public.site_content (
  content_key text primary key,
  content_data jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.site_content enable row level security;

drop policy if exists "Public can read site content" on public.site_content;
create policy "Public can read site content"
  on public.site_content for select
  to anon, authenticated
  using (true);

drop policy if exists "Authenticated staff can insert site content" on public.site_content;
create policy "Authenticated staff can insert site content"
  on public.site_content for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated staff can update site content" on public.site_content;
create policy "Authenticated staff can update site content"
  on public.site_content for update
  to authenticated
  using (true)
  with check (true);

insert into public.site_content (content_key, content_data)
values
  ('news', '[]'::jsonb),
  ('matches', '[]'::jsonb),
  ('users', '[]'::jsonb),
  ('activities', '[]'::jsonb)
on conflict (content_key) do nothing;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  role text not null default 'player' check (role in ('player','coach','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.team_events (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('match','training')),
  title text not null,
  opponent text,
  location text,
  starts_at timestamptz not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.attendance (
  event_id bigint references public.team_events(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  present boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key (event_id, user_id)
);

create table if not exists public.chat_groups (
  id bigint generated by default as identity primary key,
  name text not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_members (
  group_id bigint references public.chat_groups(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  added_by uuid references auth.users(id) on delete set null,
  primary key (group_id, user_id)
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  group_id bigint references public.chat_groups(id) on delete cascade,
  author_id uuid references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)), 'player')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

insert into public.profiles (id, display_name, email, role)
select id, coalesce(raw_user_meta_data->>'display_name', split_part(email, '@', 1)), email, 'player'
from auth.users
on conflict (id) do update set email = excluded.email;

alter table public.profiles enable row level security;
alter table public.team_events enable row level security;
alter table public.attendance enable row level security;
alter table public.chat_groups enable row level security;
alter table public.chat_members enable row level security;
alter table public.chat_messages enable row level security;

create policy "Profiles readable by signed in users" on public.profiles for select to authenticated using (true);
create policy "Users create own profile" on public.profiles for insert to authenticated with check (id = auth.uid());
create policy "Users update own profile" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy "Signed in users read events" on public.team_events for select to authenticated using (true);
create policy "Public can read matches" on public.team_events for select to anon using (kind = 'match');
create policy "Coaches create events" on public.team_events for insert to authenticated with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('coach','admin')));
create policy "Members read attendance" on public.attendance for select to authenticated using (user_id = auth.uid() or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('coach','admin')));
create policy "Players set own attendance" on public.attendance for insert to authenticated with check (user_id = auth.uid());
create policy "Players update own attendance" on public.attendance for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "Members read groups" on public.chat_groups for select to authenticated using (exists (select 1 from public.chat_members m where m.group_id = id and m.user_id = auth.uid()));
create policy "Coaches create groups" on public.chat_groups for insert to authenticated with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('coach','admin')));
create policy "Members read memberships" on public.chat_members for select to authenticated using (user_id = auth.uid() or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('coach','admin')));
create policy "Coaches manage memberships" on public.chat_members for all to authenticated using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('coach','admin'))) with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('coach','admin')));
create policy "Members read messages" on public.chat_messages for select to authenticated using (exists (select 1 from public.chat_members m where m.group_id = chat_messages.group_id and m.user_id = auth.uid()));
create policy "Members send messages" on public.chat_messages for insert to authenticated with check (author_id = auth.uid() and exists (select 1 from public.chat_members m where m.group_id = chat_messages.group_id and m.user_id = auth.uid()));

alter table public.profiles add column if not exists email text;
update public.profiles p set email = u.email from auth.users u where u.id = p.id and p.email is null;
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, email, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)), new.email,
    case when coalesce(new.raw_user_meta_data->>'app_role', 'player') = 'staff' then 'admin' else 'player' end)
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;
drop policy if exists "Admins manage profiles" on public.profiles;
create policy "Admins manage profiles" on public.profiles for update to authenticated
  using (exists (select 1 from public.profiles me where me.id = auth.uid() and me.role = 'admin'))
  with check (true);
drop policy if exists "Coaches create events" on public.team_events;
create policy "Coaches create events" on public.team_events for insert to authenticated
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('coach','admin')));
